apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-voting-app-with-tls
spec:
  rules:
  # Change with your name here
  - host: vote.<YOUR NAME>.k8s.crafteo.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vote
            port:
              number: 5000