apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  template:
    spec:
      containers:
      - name: postgres
        env:
        - name: POSTGRES_USER
          value: null
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          value: null
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        volumeMounts:
        - mountPath: /etc/postgresql/postgresql.conf
          name: config-vol
          subPath: postgresql.conf

      volumes:
      - name: config-vol
        configMap:
          name: postgres-config