apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
  {{- include "example-voting-app-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: db
  {{- include "example-voting-app-chart.selectorLabels" . | nindent 4 }}
  ports:
  - name: db-service
    port: 5432
    targetPort: 5432