apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
  {{- include "example-voting-app-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: redis
  {{- include "example-voting-app-chart.selectorLabels" . | nindent 4 }}
  ports:
  - name: redis-service
    port: 6379
    targetPort: 6379