apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    app: vote
  {{- include "example-voting-app-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: vote
  {{- include "example-voting-app-chart.selectorLabels" . | nindent 4 }}
  ports:
  - name: vote-service
    port: 5000
    targetPort: 80