# terraform init
# terraform plan
# terraform apply
# terraform destroy
#
# Deploys a Kubernetes (Kapsule) cluster on Scaleway.
# Requires Scaleway credentials, eg. via Scaleway CLI config
# (~/.config/scw/config.yaml) or SCW_ACCESS_KEY / SCW_SECRET_KEY env vars.
terraform {
  required_providers {
    scaleway = {
      source  = "scaleway/scaleway"
      version = "~> 2.45"
    }

    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
  }

  backend "local" {
    path = ".backend/backend.tfstate"
  }
}

provider "scaleway" {
  project_id = var.project_id
  region     = var.region
}

variable "project_id" {
  type        = string
  description = "Scaleway project ID"
  default     = "0d9ecb5c-3079-4d48-b133-a6714d6a9b44" # crafteo-sandbox
}

variable "region" {
  type        = string
  description = "Scaleway region"
  default     = "fr-par"
}

variable "cluster_name" {
  type        = string
  description = "Kubernetes cluster name"
  default     = "k8s-training-sandbox"
}

variable "k8s_version" {
  type        = string
  description = "Kubernetes version, latest available: 1.37.0"
  default     = "1.37.0"
}

variable "node_type" {
  type        = string
  description = "Scaleway instance type used for cluster nodes"
  default     = "DEV1-M"
}

variable "pool_size" {
  type        = number
  description = "Number of nodes in the pool"
  default     = 1
}

# Kapsule clusters require a Private Network
resource "scaleway_vpc_private_network" "training" {
  name       = "${var.cluster_name}-net"
  project_id = var.project_id
  region     = var.region
}

resource "scaleway_k8s_cluster" "training" {
  name                        = var.cluster_name
  version                     = var.k8s_version
  cni                         = "cilium"
  project_id                  = var.project_id
  region                      = var.region
  private_network_id          = scaleway_vpc_private_network.training.id
  delete_additional_resources = true
}

resource "scaleway_k8s_pool" "training" {
  cluster_id  = scaleway_k8s_cluster.training.id
  name        = "default"
  node_type   = var.node_type
  size        = var.pool_size
  min_size    = var.pool_size
  max_size    = var.pool_size
  autohealing = true
}

# Kubeconfig generated by Scaleway, written locally so kubectl can
# reach the cluster (contains client certificates: not version controlled)
resource "local_sensitive_file" "kubeconfig" {
  content  = scaleway_k8s_cluster.training.kubeconfig[0].config_file
  filename = "${path.module}/.backend/kubeconfig.yaml"
}

output "cluster_id" {
  value = scaleway_k8s_cluster.training.id
}

output "kubeconfig_path" {
  value = abspath(local_sensitive_file.kubeconfig.filename)
}
