apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-certificate-secret
spec:
  secretName: crafteo-tls
  commonName: vote.k8s.crafteo.io
  dnsNames:
  - vote.k8s.crafteo.io
  - result.k8s.crafteo.io
  issuerRef:
    name: <issuer-name>
    kind: Issuer # or ClusterIssuer
