apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-certificate-secret
spec:
  # Must match ingress secret name
  secretName: ingress-certificate-secret
  commonName: vote.<YOUR_NAME>.k8s.crafteo.io
  dnsNames:
  - vote.<YOUR_NAME>.k8s.crafteo.io
  - result.<YOUR_NAME>.k8s.crafteo.io
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
